### ISSUE TITLE
Approver body

### ISSUE THREAD

**Issue by couci** [MichaelKohler/remo-mean-time-approval#6]
On the last version we are having the following bodies:
- council
- single council
- review-team

I don't see single review-team is that because it is too early and we don't have a member assigned to a single bug yet?

**Comment by MichaelKohler** [comment]
As far as I know there have been 2 bugs assigned so single review team members. The other two that I could find are assigned to the full team and therefore are correct (two times "review-team" is in the list.

The ones assigned to single review team members are:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1308672
- https://bugzilla.mozilla.org/show_bug.cgi?id=1303546

The whiteboard says 'Review Team assigned' though my script will check for 'Review Team member Assigned' (see https://github.com/MichaelKohler/remo-mean-time-approval/issues/2#issue-180942847), we need to make sure that we do not use different formats to make it easier. These are empty in the list due to that.

The Budget SOP says 'Review Team assigned' as well, so I think we should change the script to check for that? (https://wiki.mozilla.org/ReMo/SOPs/Budget/Process)

**Comment by MichaelKohler** [comment]
Further, I think I should also do a lowercase check on those, will fix that as well :)

**Comment by couci** [comment]
yeah, let's follow the SOP definitions since those are the ones Kiki uses.

thanks :)
